apiVersion: v1
kind: Service
metadata:
  name: kubernetes-api-service
  labels:
    app: kubernetes-api
spec:
  selector:
    app: kubernetes-api
  ports:
    - protocol: TCP
      port: 3000 #Service port
      targetPort: 3000 #Container port
  type: NodePort #change to Loadbalancer if running in cloud